# Site settings
title: Rails Mama
email: reeddetorres@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mother of Two Juggles Family 
  While Learning to Code
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://julietorres.me" # the base hostname & protocol for your site
twitter_username: JulieTorero
github_username:  JTorr

# Build settings
markdown: kramdown
highlighter: pygments
