# Site settings
title: Rails Mama
email: railsmama@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Lighthearted Take on Life in the Tech World 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://julietorres.me" # the base hostname & protocol for your site
twitter_username: JulieTorero
github_username:  JTorr

# Build settings
markdown: kramdown
highlighter: pygments
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

